/**
 * AUTO-GENERATED by A4 Test Generator — do not edit manually.
 * Source spec: specs/ecommerce.yaml → event: view_item
 * Regenerate by merging a spec change to main.
 */

import { test, expect } from '@playwright/test';

// ── helpers ───────────────────────────────────────────────────────────────────

async function waitForDataLayerEvent(page, eventName, timeoutMs = 8000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const found = await page.evaluate((name) => {
      return (window.dataLayer || []).find(e => e.event === name) || null;
    }, eventName);
    if (found) return found;
    await page.waitForTimeout(250);
  }
  throw new Error(`dataLayer event "${eventName}" not found within ${timeoutMs}ms`);
}

function getAllDataLayerEvents(page, eventName) {
  return page.evaluate((name) => {
    return (window.dataLayer || []).filter(e => e.event === name);
  }, eventName);
}

// ── tests ─────────────────────────────────────────────────────────────────────

test.describe('view_item', () => {
  let eventPayload;

  test.beforeEach(async ({ page }) => {
    // Trigger: page_load on a product detail page
    await page.goto(process.env.TEST_URL + '/products/sample-product');
    eventPayload = await waitForDataLayerEvent(page, 'view_item');
  });

  // 1. Event presence
  test('event fires on product page load', async ({ page }) => {
    expect(
      eventPayload,
      'view_item was not found in window.dataLayer after page load'
    ).toBeTruthy();
  });

  // 2. Required parameters — presence
  test('ecommerce object is present', async ({ page }) => {
    expect(
      eventPayload.ecommerce,
      'ecommerce object is missing from view_item payload'
    ).toBeDefined();
  });

  test('ecommerce.currency is present', async ({ page }) => {
    expect(
      eventPayload.ecommerce?.currency,
      'ecommerce.currency is missing from view_item payload'
    ).toBeDefined();
  });

  test('ecommerce.value is present', async ({ page }) => {
    expect(
      eventPayload.ecommerce?.value,
      'ecommerce.value is missing from view_item payload'
    ).toBeDefined();
  });

  test('ecommerce.items array is present', async ({ page }) => {
    expect(
      eventPayload.ecommerce?.items,
      'ecommerce.items is missing from view_item payload'
    ).toBeDefined();
  });

  // 3. Type validation
  test('ecommerce.currency is a non-empty string', async ({ page }) => {
    const currency = eventPayload.ecommerce?.currency;
    expect(
      typeof currency === 'string' && currency.length > 0,
      `ecommerce.currency must be a non-empty string, got ${typeof currency} (value: ${currency})`
    ).toBe(true);
  });

  test('ecommerce.value is a number', async ({ page }) => {
    const value = eventPayload.ecommerce?.value;
    expect(
      typeof value === 'number' && !isNaN(value),
      `ecommerce.value must be a number, got ${typeof value} (value: ${value})`
    ).toBe(true);
  });

  test('ecommerce.items is a non-empty array', async ({ page }) => {
    const items = eventPayload.ecommerce?.items;
    expect(
      Array.isArray(items) && items.length > 0,
      `ecommerce.items must be a non-empty array, got ${typeof items}`
    ).toBe(true);
  });

  // 4. Enum validation
  test('ecommerce.currency is a valid ISO 4217 code', async ({ page }) => {
    const VALID_CURRENCIES = ['EUR', 'USD', 'GBP', 'SEK', 'NOK', 'DKK', 'CHF'];
    const currency = eventPayload.ecommerce?.currency;
    expect(
      VALID_CURRENCIES.includes(currency),
      `ecommerce.currency "${currency}" is not in allowed list: ${VALID_CURRENCIES.join(', ')}`
    ).toBe(true);
  });

  // 5. Items shape
  test('each item has item_id', async ({ page }) => {
    const items = eventPayload.ecommerce?.items || [];
    for (const item of items) {
      expect(
        typeof item.item_id === 'string' && item.item_id.length > 0,
        `item_id must be a non-empty string, got ${typeof item.item_id} (value: ${item.item_id})`
      ).toBe(true);
    }
  });

  test('each item has item_name', async ({ page }) => {
    const items = eventPayload.ecommerce?.items || [];
    for (const item of items) {
      expect(
        typeof item.item_name === 'string' && item.item_name.length > 0,
        `item_name must be a non-empty string, got ${typeof item.item_name}`
      ).toBe(true);
    }
  });

  test('each item price is a number', async ({ page }) => {
    const items = eventPayload.ecommerce?.items || [];
    for (const item of items) {
      expect(
        typeof item.price === 'number' && !isNaN(item.price),
        `item.price must be a number, got ${typeof item.price} (value: ${item.price})`
      ).toBe(true);
    }
  });

  // 6. Business rule: fires only once per page load (no duplicate)
  test('view_item fires exactly once per page load', async ({ page }) => {
    const allOccurrences = await getAllDataLayerEvents(page, 'view_item');
    expect(
      allOccurrences.length,
      `view_item fired ${allOccurrences.length} times — expected exactly 1`
    ).toBe(1);
  });
});
